apiVersion: v1
kind: Pod
metadata:
  labels:
    run: trainer
  name: trainer
  namespace: mlops
spec:
  containers:
  - args:
    - python
    - /app/train.py
    env:
    - name: MLFLOW_TRACKING_URI
      value: http://mlflow.mlops:5000
    - name: MLFLOW_S3_ENDPOINT_URL
      value: http://minio.mlops:9000
    - name: AWS_ACCESS_KEY_ID
      value: minioadmin
    - name: AWS_SECRET_ACCESS_KEY
      value: minioadmin
    image: mlops/trainer:0.1.0
    name: trainer
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
