apiVersion: apps/v1
kind: Deployment
metadata: { name: model-serving-dev, namespace: mlops }
spec:
  replicas: 1
  selector: { matchLabels: { app: model-serving, env: dev } }
  template:
    metadata:
      labels: { app: model-serving, env: dev }
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: serving
        image: mlops/serving:0.1.0
        env:
        - { name: MLFLOW_TRACKING_URI, value: http://mlflow.mlops:5000 }
        - { name: MODEL_NAME, value: demo-classifier }
        - { name: MODEL_STAGE, value: Staging }
        - { name: API_KEY, valueFrom: { secretKeyRef: { name: mlops-secrets, key: API_KEY } } }
        - { name: MLFLOW_S3_ENDPOINT_URL, value: http://minio.mlops:9000 }
        - { name: AWS_ACCESS_KEY_ID, value: minioadmin }
        - { name: AWS_SECRET_ACCESS_KEY, value: minioadmin }
        ports:
        - { containerPort: 8000 }