apiVersion: v1
kind: Service
metadata:
  name: model-serving
  namespace: mlops
  labels: { app: model-serving }
spec:
  selector: { app: model-serving }
  ports:
  - { name: http, port: 8000, targetPort: 8000 }