apiVersion: apps/v1
kind: Deployment
metadata: { name: minio, namespace: mlops }
spec:
  replicas: 1
  selector: { matchLabels: { app: minio } }
  template:
    metadata: { labels: { app: minio } }
    spec:
      containers:
      - name: minio
        image: minio/minio:RELEASE.2025-09-07T16-13-09Z
        args: ["server", "/data", "--console-address", ":9001"]
        env:
        - name: MINIO_ROOT_USER
          valueFrom: { secretKeyRef: { name: mlops-secrets, key: AWS_ACCESS_KEY_ID } }
        - name: MINIO_ROOT_PASSWORD
          valueFrom: { secretKeyRef: { name: mlops-secrets, key: AWS_SECRET_ACCESS_KEY } }
        ports:
        - { containerPort: 9000 }
        - { containerPort: 9001 }
---
apiVersion: v1
kind: Service
metadata: { name: minio, namespace: mlops }
spec:
  selector:
    app: minio
  ports:
  - name: api
    port: 9000
    targetPort: 9000
  - name: console
    port: 9001
    targetPort: 9001
