apiVersion: apps/v1
kind: Deployment
metadata: { name: mlflow, namespace: mlops }
spec:
  replicas: 1
  selector: { matchLabels: { app: mlflow } }
  template:
    metadata:
      labels: { app: mlflow }
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
    spec:
      containers:
      - name: mlflow
        image: mlops/mlflow:0.1.0
        env:
        - name: MLFLOW_S3_ENDPOINT_URL
          value: http://minio.mlops:9000
        - name: AWS_ACCESS_KEY_ID
          valueFrom: { secretKeyRef: { name: mlops-secrets, key: AWS_ACCESS_KEY_ID } }
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom: { secretKeyRef: { name: mlops-secrets, key: AWS_SECRET_ACCESS_KEY } }
        - name: BACKEND_URI
          value: postgresql://mlflow:mlflow@mlflow-pg.mlops:5432/mlflow
        - name: ARTIFACT_ROOT
          value: s3://mlflow-artifacts
        ports:
        - { containerPort: 5000 }
---
apiVersion: v1
kind: Service
metadata: { name: mlflow, namespace: mlops }
spec:
  selector: { app: mlflow }
  ports:
  - { port: 5000, targetPort: 5000 }