apiVersion: apps/v1
kind: Deployment
metadata: { name: mlflow-pg, namespace: mlops }
spec:
  replicas: 1
  selector: { matchLabels: { app: mlflow-pg } }
  template:
    metadata: { labels: { app: mlflow-pg } }
    spec:
      containers:
      - name: pg
        image: postgres:16
        env:
        - { name: POSTGRES_PASSWORD, value: mlflow }
        - { name: POSTGRES_USER, value: mlflow }
        - { name: POSTGRES_DB, value: mlflow }
        ports:
        - { containerPort: 5432 }
---
apiVersion: v1
kind: Service
metadata: { name: mlflow-pg, namespace: mlops }
spec:
  selector: { app: mlflow-pg }
  ports:
  - { port: 5432, targetPort: 5432 }